#!/usr/bin/env python3
"""Compiles src/gpu/CosmicKernels.cu to PTX and writes it as a C++ header.

The plug-in carries its CUDA kernels as PTX, which the NVIDIA driver compiles
for the installed GPU the first time the effect renders on it (and caches). So
the build needs no CUDA toolkit: only NVRTC, NVIDIA's runtime compiler
library, which this script loads with ctypes. It is on PyPI:

    python3 -m pip install "nvidia-cuda-nvrtc-cu12==12.4.127"

The version matters. PTX carries an ISA version and a driver refuses PTX newer
than itself; NVRTC 12.4 writes ISA 8.4, which every driver from R550 onwards
accepts, including all drivers for RTX 50-series GPUs. compute_75 (Turing)
PTX runs on Turing and everything after it.

The generated header is committed, so building the plug-in does not need this
script; run it after changing the kernels or anything they include.

Usage: build_ptx.py [--nvrtc path/to/libnvrtc.so] [--output src/gpu/CosmicKernelsPtx.h]
       build_ptx.py --check   fails if the header is older than the kernel sources
"""

import argparse
import ctypes
import glob
import hashlib
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
KERNELS = os.path.join(ROOT, "src", "gpu", "CosmicKernels.cu")
# Everything the kernels include: a change to any of them changes the PTX.
SOURCES = [
    KERNELS,
    os.path.join(ROOT, "src", "gpu", "KernelParams.h"),
    os.path.join(ROOT, "src", "core", "Shared.h"),
]
ARCH = "compute_75"


def source_fingerprint():
    digest = hashlib.sha256()
    for path in SOURCES:
        with open(path, "rb") as handle:
            # Line endings do not change the PTX.
            digest.update(handle.read().replace(b"\r\n", b"\n"))
    return digest.hexdigest()


def find_nvrtc(explicit):
    if explicit:
        return explicit
    candidates = []
    try:
        import nvidia.cuda_nvrtc  # noqa: F401 - only used to locate the library

        base = os.path.dirname(nvidia.cuda_nvrtc.__file__)
        candidates += glob.glob(os.path.join(base, "lib", "libnvrtc.so*"))
        candidates += glob.glob(os.path.join(base, "bin", "nvrtc64_*.dll"))
    except ImportError:
        pass
    candidates += ["libnvrtc.so.12", "libnvrtc.so", "nvrtc64_120_0.dll"]
    for candidate in candidates:
        if "builtins" in candidate or ".alt." in candidate:
            continue
        try:
            ctypes.CDLL(candidate)
            return candidate
        except OSError:
            continue
    raise SystemExit("NVRTC not found; pip install nvidia-cuda-nvrtc-cu12==12.4.127 or pass --nvrtc")


def compile_ptx(nvrtc_path):
    lib = ctypes.CDLL(nvrtc_path)
    with open(KERNELS, "rb") as handle:
        source = handle.read()

    version_major = ctypes.c_int()
    version_minor = ctypes.c_int()
    lib.nvrtcVersion(ctypes.byref(version_major), ctypes.byref(version_minor))

    program = ctypes.c_void_p()
    result = lib.nvrtcCreateProgram(ctypes.byref(program), source, b"CosmicKernels.cu", 0, None, None)
    if result != 0:
        raise SystemExit("nvrtcCreateProgram failed: %d" % result)

    options = [
        ("--gpu-architecture=" + ARCH).encode(),
        b"--std=c++17",
        ("--include-path=" + os.path.join(ROOT, "src")).encode(),
        # Precise maths, like the CPU renderer: the two are compared in tests.
        b"--prec-div=true",
        b"--prec-sqrt=true",
    ]
    array = (ctypes.c_char_p * len(options))(*options)
    result = lib.nvrtcCompileProgram(program, len(options), array)

    log_size = ctypes.c_size_t()
    lib.nvrtcGetProgramLogSize(program, ctypes.byref(log_size))
    log = ctypes.create_string_buffer(log_size.value)
    lib.nvrtcGetProgramLog(program, log)
    if log.value.strip():
        sys.stderr.write(log.value.decode(errors="replace") + "\n")
    if result != 0:
        raise SystemExit("nvrtcCompileProgram failed: %d" % result)

    ptx_size = ctypes.c_size_t()
    lib.nvrtcGetPTXSize(program, ctypes.byref(ptx_size))
    ptx = ctypes.create_string_buffer(ptx_size.value)
    lib.nvrtcGetPTX(program, ptx)
    lib.nvrtcDestroyProgram(ctypes.byref(program))
    return ptx.raw, "%d.%d" % (version_major.value, version_minor.value)


def write_header(path, ptx, nvrtc_version, fingerprint):
    # A byte array rather than a string literal: MSVC limits string literals to
    # 64 KB, and the PTX is larger than that.
    lines = [
        "#pragma once",
        "",
        "// Generated by tools/build_ptx.py from src/gpu/CosmicKernels.cu - do not edit.",
        "// NVRTC %s, %s. The array is NUL-terminated PTX text." % (nvrtc_version, ARCH),
        "// Sources: %s" % fingerprint,
        "",
        "namespace cosmic {",
        "",
        "constexpr unsigned long kCosmicKernelsPtxSize = %d;" % len(ptx),
        "",
        "alignas(8) static const unsigned char kCosmicKernelsPtx[] = {",
    ]
    for offset in range(0, len(ptx), 20):
        chunk = ptx[offset:offset + 20]
        lines.append("    " + ", ".join("0x%02x" % byte for byte in chunk) + ",")
    lines += ["};", "", "}  // namespace cosmic", ""]
    with open(path, "w", encoding="ascii", newline="\n") as handle:
        handle.write("\n".join(lines))


def main(argv):
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--nvrtc", default="")
    parser.add_argument("--output", default=os.path.join(ROOT, "src", "gpu", "CosmicKernelsPtx.h"))
    parser.add_argument("--ptx", default="", help="also write the raw PTX here")
    parser.add_argument("--check", action="store_true", help="only check the header is up to date")
    args = parser.parse_args(argv)

    fingerprint = source_fingerprint()
    if args.check:
        try:
            with open(args.output, "r", encoding="ascii") as handle:
                match = re.search(r"// Sources: ([0-9a-f]{64})", handle.read())
        except OSError:
            match = None
        if match is None or match.group(1) != fingerprint:
            print("%s is out of date: run tools/build_ptx.py" % os.path.relpath(args.output, ROOT))
            return 1
        print("PTX header matches the kernel sources")
        return 0

    ptx, version = compile_ptx(find_nvrtc(args.nvrtc))
    if not ptx.endswith(b"\0"):
        ptx += b"\0"
    write_header(args.output, ptx, version, fingerprint)
    if args.ptx:
        with open(args.ptx, "wb") as handle:
            handle.write(ptx.rstrip(b"\0"))
    entries = [line.split()[-1] for line in ptx.decode(errors="replace").splitlines() if line.startswith(".visible .entry")]
    print("PTX: NVRTC %s, %d bytes, kernels: %s" % (version, len(ptx), ", ".join(e.rstrip("(") for e in entries)))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
